# For the low-power microphone of the AOP (J700): 16 kHz, two channels

SectionDevice."Mic" {
	Comment "Microphone"

	Value {
		TQ Voice
		CaptureChannels "2"
		CapturePriority 100
		CapturePCM "hw:${CardId},0"
	}
}
